import fs from "node:fs/promises";
import path from "node:path";
import type { ApiManifest } from "./types";

function toParamsType(routePath: string): string {
	const names = Array.from(
		routePath.matchAll(/:([A-Za-z0-9_]+)/g),
		(match) => match[1],
	).filter(Boolean);

	if (names.length === 0) return "{}";

	return `{ ${names.map((name) => `${JSON.stringify(name)}: string`).join("; ")} }`;
}

export async function writeVirtualApiTypes(
	outDir: string,
	manifest: ApiManifest,
): Promise<void> {
	await fs.mkdir(outDir, { recursive: true });

	const routeEntries = manifest.routes.map((route) => {
		const methods = route.methods
			.map(
				(method) =>
					`${method}: ClientFn<typeof import("${toImportPath(route.filePath)}").${method}, ${toParamsType(route.routePath)}>;`,
			)
			.join("\n");

		return `  "${route.routePath}": {\n${methods}\n  };`;
	});

	const source = `
// Generated by fahhh. Do not edit.

type AwaitedReturn<T> = T extends Promise<infer U> ? U : T;

type HandlerReturn<T> =
  T extends (...args: unknown[]) => infer R
    ? AwaitedReturn<R> extends Response
      ? Response
      : AwaitedReturn<R>
    : never;

type FirstArg<T> =
  T extends (arg: infer A, ...args: unknown[]) => unknown ? A : never;

type HandlerBody<T> =
  T extends (...args: infer Args) => unknown
    ? Args extends []
      ? undefined
      : FirstArg<T> extends { json(): Promise<infer B> }
        ? B
        : undefined
    : undefined;

type ClientInput<TBody, TParams> =
  keyof TParams extends never
    ? TBody extends undefined
      ? void
      : TBody
    : TBody extends undefined
      ? { params: TParams; headers?: HeadersInit }
      : { params: TParams; body: TBody; headers?: HeadersInit };    

type ClientFn<THandler, TParams> =
  ClientInput<HandlerBody<THandler>, TParams> extends void
    ? () => Promise<HandlerReturn<THandler>>
    : (input: ClientInput<HandlerBody<THandler>, TParams>) => Promise<HandlerReturn<THandler>>;

declare module "virtual:api" {
  const api: {
${routeEntries.join("\n")}
  };

  export default api;
}
`.trimStart();

	await fs.writeFile(path.join(outDir, "virtual-api.d.ts"), source);
}

function toImportPath(filePath: string): string {
	return filePath.replaceAll("\\", "/");
}
