import fs from "node:fs/promises";
import path from "node:path";
import type { ApiManifest } from "@fahhh/deploy-core";

function toParamsType(routePath: string): string {
	const entries = routePath
		.split("/")
		.filter(Boolean)
		.flatMap((segment) => {
			if (!segment.startsWith(":")) return [];

			if (segment.endsWith("*?")) {
				return `${JSON.stringify(segment.slice(1, -2))}?: string[]`;
			}

			if (segment.endsWith("*")) {
				return `${JSON.stringify(segment.slice(1, -1))}: string[]`;
			}

			return `${JSON.stringify(segment.slice(1))}: string`;
		});

	return entries.length === 0 ? "{}" : `{ ${entries.join("; ")} }`;
}

export async function writeVirtualApiTypes(
	outDir: string,
	manifest: ApiManifest,
): Promise<void> {
	await fs.mkdir(outDir, { recursive: true });

	const routeEntries = manifest.routes.map((route) => {
		const methods = route.methods
			.map(
				(method) =>
					`${method}: ClientFn<typeof import(${JSON.stringify(toImportPath(outDir, route.filePath))}).${method}, ${toParamsType(route.routePath)}>;`,
			)
			.join("\n");

		return `  "${route.routePath}": {\n${methods}\n  };`;
	});

	const source = `
// Generated by fahhh. Do not edit.

declare module "virtual:api" {
  type HandlerReturn<T> =
    T extends (...args: infer _Args) => infer R ? Awaited<R> : never;

  type HandlerBody<T> =
    T extends (...args: infer Args) => unknown
      ? Args extends [infer Request, ...unknown[]]
        ? Request extends { json(): Promise<infer Body> }
          ? Body
          : undefined
        : undefined
      : undefined;

  type QueryPrimitive = string | number | boolean | null | undefined;
  type QueryValue = QueryPrimitive | QueryPrimitive[];
  type QueryInput = Record<string, QueryValue>;

  type ClientOptions = {
    headers?: HeadersInit;
    signal?: AbortSignal;
    query?: QueryInput;
  };

  type ClientInput<TBody, TParams> =
    keyof TParams extends never
      ? TBody extends undefined
        ? ClientOptions | void
        : ClientOptions & { body: TBody }
      : TBody extends undefined
        ? ClientOptions & { params: TParams }
        : ClientOptions & { params: TParams; body: TBody };

  type ClientFn<THandler, TParams> =
    ClientInput<HandlerBody<THandler>, TParams> extends void
      ? () => Promise<HandlerReturn<THandler>>
      : undefined extends ClientInput<HandlerBody<THandler>, TParams>
        ? (input?: ClientInput<HandlerBody<THandler>, TParams>) => Promise<HandlerReturn<THandler>>
        : (input: ClientInput<HandlerBody<THandler>, TParams>) => Promise<HandlerReturn<THandler>>;

  const api: {
${routeEntries.join("\n")}
  };

  export default api;
}
`.trimStart();

	await fs.writeFile(path.join(outDir, "virtual-api.d.ts"), source);
}

function toImportPath(outDir: string, filePath: string): string {
	const withoutExtension = filePath.replace(/\.[cm]?[tj]sx?$/, "");
	let relative = path.relative(outDir, withoutExtension).replaceAll("\\", "/");
	if (!relative.startsWith(".")) relative = `./${relative}`;
	return relative;
}
